sudo: required
services:
  - docker
before_install:
  - docker build -t hady1100/react-test -f ./client/DockerFile.dev ./client
script:
  - docker run hady1100/react-test npm test -- --coverage
after_success:
  - docker build -t hady1100/multi-client ./client
  - docker build -t hady1100/multi-nginx ./nginx
  - docker build -t hady1100/multi-server ./server
  - docker build -t hady1100/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hady1100/multi-client
  - docker push hady1100/multi-nginx
  - docker push hady1100/multi-server
  - docker push hady1100/multi-worker